# Generated by Django 4.1.11 on 2023-09-28 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    replaces = [('fleaapi', '0001_initial'), ('fleaapi', '0002_alter_user_email')]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                (
                    'id',
                    models.AutoField(db_index=True, primary_key=True, serialize=False),
                ),
                ('name', models.CharField(max_length=255)),
                (
                    'email',
                    models.EmailField(db_index=True, max_length=255, unique=True),
                ),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to='fleaapi.user'
                    ),
                ),
            ],
        ),

        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('seller_id', models.CharField(max_length=255)),
                ('category_id', models.CharField(max_length=255)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('item_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('item_id', models.CharField(max_length=255)),
                ('pickup_option', models.CharField(max_length=255)),
                ('payment', models.CharField(max_length=255)),
            ],
        ),

        
    ]
