# Generated by Django 4.1.11 on 2023-09-28 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('fleaapi', '0001_squashed_0002_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('image', models.CharField(max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                (
                    'category_id',
                    models.ForeignKey(
                        blank=True,
                        max_length=255,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='fleaapi.category',
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='address',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pickup_option', models.CharField(max_length=255)),
                ('payment', models.CharField(max_length=255)),
                (
                    'item_id',
                    models.ForeignKey(
                        max_length=255,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='fleaapi.item',
                    ),
                ),
                (
                    'user_id',
                    models.ForeignKey(
                        max_length=255,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='fleaapi.user',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='seller_id',
            field=models.ForeignKey(
                max_length=255,
                on_delete=django.db.models.deletion.CASCADE,
                to='fleaapi.sellerprofile',
            ),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                (
                    'item_id',
                    models.ForeignKey(
                        max_length=255,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='fleaapi.item',
                    ),
                ),
                (
                    'user_id',
                    models.ForeignKey(
                        max_length=255,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='fleaapi.user',
                    ),
                ),
            ],
        ),
    ]
