name: Django CI Release - Aws

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: null

jobs:          
  build-and-deploy:
    runs-on: [self-hosted, AWS, Prod]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Building web app
        run: |
          bash scripts/postbuild.sh