name: Django CI Release - Aws

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: null

jobs:
  build-and-deploy:
    runs-on: [self-hosted, AWS, Prod]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Frontend Build
        run: |
          pushd frontend
          npm ci
          npm run build --if-present
          rm -rf ./node_modules # remove for smaller package size
          popd
      - name: Building web app
        run: |
          bash scripts/postbuild.sh
      - name: Restart web service
        run: |
          sudo systemctl restart emperor.uwsgi.service