name: Django CI Release - Aws

on:
  push:
    branches: [ "main", "tianpei/fix_aws" ]
  workflow_dispatch: null

jobs:
  build-frontend:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Frontend Build
        run: |
          pushd frontend
          sed -i -E '/^\s+\/\//d' package.json # fix the package.json
          # npm ci
          # use follow 2 lines to fix broken package-lock.json
          npm install
          npm install --save-dev @babel/plugin-proposal-private-property-in-object
          npm run build --if-present
          rm -rf ./node_modules # remove for smaller package size
          popd
      - name: Push artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend
          path: frontend/build

  build-and-deploy:
    runs-on: [self-hosted, AWS, Prod]
    needs: build-frontend
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: frontend
          path: frontend/build
      - name: Building web app
        run: |
          bash scripts/postbuild.sh
      - name: Restart web service
        run: |
          sudo systemctl restart emperor.uwsgi.service