name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  linting:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Black
        uses: microsoft/action-python@0.7.0
        with:
          python_version: 3.9
          black: true
          workdir: .
          
  build-and-coverage:
    runs-on: ubuntu-20.04
    permissions:
      checks: write
      contents: read
      deployments: write
      pull-requests: write
      statuses: write
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          bash runtest.sh --cov-report term --cov-report xml:/tmp/flea_coverage.xml --cov
      - name: Get Coverage
        uses: orgoro/coverage@v3.1
        with:
            coverageFile: /tmp/flea_coverage.xml
            token: ${{ secrets.GITHUB_TOKEN }}
            thresholdAll: 0.6
            thresholdNew: 0.75
            thresholdModified: 0.75
